kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: cluster-sustainable-computing-sandbox
networking:
  # tweaks
  ipFamily: dual  # dual stack ipv4 + ipv6
  kubeProxyMode: "ipvs"
  # the following are all defaults, but listed explicitly for clarity
  apiServerAddress: "127.0.0.1"
  apiServerPort: 6443
  podSubnet: "10.244.0.0/16"
  serviceSubnet: "10.96.0.0/12"  # fd00:10:96::/112 for ipv6
  disableDefaultCNI: false # by default uses kindnetd
# node config
nodes:
- role: control-plane
  image: kindest/node:v1.27.3@sha256:3966ac761ae0136263ffdb6cfd4db23ef8a83cba8a463690e98317add2c9ba72
  kubeadmConfigPatches:
  - |
    kind: ClusterConfiguration
    apiServer:
        extraArgs:
          enable-admission-plugins: NodeRestriction,MutatingAdmissionWebhook,ValidatingAdmissionWebhook 
  extraPortMappings:
  - containerPort: 80
    hostPort: 80
  extraMounts:
  # needed for kepler
  - hostPath: /proc
    containerPath: /proc-host
  - hostPath: /usr/src
    containerPath: /usr/src
- role: worker
  image: kindest/node:v1.27.3@sha256:3966ac761ae0136263ffdb6cfd4db23ef8a83cba8a463690e98317add2c9ba72
  extraMounts:
  # needed for kepler
  - hostPath: /proc
    containerPath: /proc-host
  - hostPath: /usr/src
    containerPath: /usr/src